package com.hhkungfu.backend.common.exception;

public enum ErrorConstants {
    // --- General Errors ---
    UNAUTHORIZED("UNAUTHORIZED"),
    FORBIDDEN("FORBIDDEN"),
    METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),
    CONTENT_TYPE_NOT_SUPPORTED("CONTENT_TYPE_NOT_SUPPORTED"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    VALIDATION_ERROR("VALIDATION_ERROR"),
    INVALID_ARGUMENT("INVALID_ARGUMENT"),

    // --- Auth & User Errors ---
    USER_NOT_FOUND("USER_NOT_FOUND"),
    EMAIL_ALREADY_EXISTS("EMAIL_ALREADY_EXISTS"),
    EMAIL_ALREADY_VERIFIED("EMAIL_ALREADY_VERIFIED"),
    EMAIL_NOT_VERIFIED("EMAIL_NOT_VERIFIED"),
    USERNAME_ALREADY_EXISTS("USERNAME_ALREADY_EXISTS"),
    INVALID_CREDENTIALS("INVALID_CREDENTIALS"),
    ACCOUNT_DISABLED("ACCOUNT_DISABLED"),
    OAUTH_ACCOUNT("OAUTH_ACCOUNT"),
    INVALID_TOKEN("INVALID_TOKEN"),
    REFRESH_TOKEN_INVALID("REFRESH_TOKEN_INVALID"),

    // --- Password & OTP Errors ---
    INVALID_PASSWORD("INVALID_PASSWORD"),
    SAME_PASSWORD("SAME_PASSWORD"),
    WEAK_PASSWORD("WEAK_PASSWORD"),
    OTP_EXPIRED("OTP_EXPIRED"),
    OTP_INVALID("OTP_INVALID"),
    OTP_RATE_LIMIT("OTP_RATE_LIMIT"),

    // --- Anime & Content Errors ---
    ANIME_NOT_FOUND("ANIME_NOT_FOUND"),
    SLUG_ALREADY_EXISTS("SLUG_ALREADY_EXISTS"),
    GENRE_NOT_FOUND("GENRE_NOT_FOUND"),
    GENRE_ALREADY_EXISTS("GENRE_ALREADY_EXISTS"),
    STUDIO_NOT_FOUND("STUDIO_NOT_FOUND"),
    EPISODE_NOT_FOUND("EPISODE_NOT_FOUND"),

    // --- Interaction Errors ---
    ALREADY_BOOKMARKED("ALREADY_BOOKMARKED"),
    BOOKMARK_NOT_FOUND("BOOKMARK_NOT_FOUND"),
    COMMENT_NOT_FOUND("COMMENT_NOT_FOUND"),
    NESTED_REPLY_NOT_ALLOWED("NESTED_REPLY_NOT_ALLOWED"),

    // --- Episode & Video Errors ---
    EPISODE_NUMBER_EXISTS("EPISODE_NUMBER_EXISTS"),
    EPISODE_NOT_READY("EPISODE_NOT_READY"),
    VIP_REQUIRED("VIP_REQUIRED"),
    VIDEO_ALREADY_PROCESSING("VIDEO_ALREADY_PROCESSING"),
    UPLOAD_FAILED("UPLOAD_FAILED"),
    TRANSCODE_JOB_NOT_FOUND("TRANSCODE_JOB_NOT_FOUND");

    private final String code;

    ErrorConstants(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
